baseURL = "https://ja.id.au"
title = "josh adams"
theme = ["etch", "hugo-shortcode-gallery"]
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true

[params]
  description = "home of josh adams, not the jockey though."
  copyright = "copyright © 2022 josh adams"
  dark = "true"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10
	
  [[menu.main]]
    identifier = "now"
    name = "now"
    title = "now"
    url = "/now"
    weight = 12

  [[menu.main]]
    identifier = "Gallery"
    name = "Gallery"
    title = "Gallery"
    url = "/gallery"
    weight = 13

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 100

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[Frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', ':git', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
