baseURL = "https://ja.id.au"
title = "josh adams"
theme = ["etch"]
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "home of josh adams, not the jockey though."
  copyright = "copyright © 2022 josh adams"
  dark = "true"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10
	
  [[menu.main]]
    identifier = "now"
    name = "now"
    title = "now"
    url = "/now"
    weight = 12

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 100

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = false
